### ISSUE TITLE
Capstone project: set up the kanban board

### ISSUE THREAD

**Issue by Sboursen** [Sboursen/catalog-capstone-project#29]
Hi :wave: 
In this project we are a group of three people:

- Team member 1: @mirouhml 
- Team member 2: @NasKhalil 
- Team member 3: @Sboursen 

Please find a below-attached link to our project: 
:point_right: [Project link](https://github.com/Sboursen/catalog-capstone-project/projects/1)

Cheers,

**Comment by Rustamxon7** [comment]
## Hi team👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```
